export const exams = [
  {
    id: 1,
    slug: 'kharidar',
    name: 'खरिदार',
    en: 'Kharidar',
    level: 'Assistant',
    levelCode: 'assistant',
    service: 'Administration / Accounts / Judiciary / Parliamentary',
    papers: '3 Papers + Computer Test',
    vacancy: 'High competition',
    description: 'Entry-level clerical position across multiple services. Involves documentation, file management, and administrative support.',
    posts: 'Clerical duties, record management',
    salary: '₦ 13,000 - 18,000',
    service_colors: ['#1E40AF', '#10B981'],
  },
  {
    id: 2,
    slug: 'nasu',
    name: 'नायब सुब्बा',
    en: 'Nayab Subba (NaSu)',
    level: 'Assistant',
    levelCode: 'assistant',
    service: 'Administration / Accounts / Judiciary / Parliamentary',
    papers: '3 Papers',
    vacancy: 'Very competitive',
    description: 'Mid-level clerical position. Requires experience and higher qualifications. Primary administrative responsibility.',
    posts: 'Administrative duties, supervision',
    salary: '₦ 16,000 - 22,000',
    service_colors: ['#1E40AF', '#10B981'],
  },
  {
    id: 3,
    slug: 'sakha-adhikrit',
    name: 'शाखा अधिकृत',
    en: 'Sakha Adhikrit (Section Officer)',
    level: 'Officer',
    levelCode: 'officer',
    service: 'Administration / Accounts / Foreign Affairs / Parliamentary',
    papers: '4 Papers',
    vacancy: 'Gazetted 3rd Class',
    description: 'Senior officer-level position. Gazetted position requiring comprehensive knowledge and decision-making skills.',
    posts: 'Section-level management, policy implementation',
    salary: '₦ 24,000 - 35,000',
    service_colors: ['#1E40AF', '#F59E0B'],
  },
  {
    id: 4,
    slug: 'technical-assistant',
    name: 'प्राविधिक सहायक',
    en: 'Technical Assistant',
    level: 'Technical',
    levelCode: 'technical',
    service: 'Engineering / Survey / Education / Statistics',
    papers: '2-3 Papers',
    vacancy: 'Service specific',
    description: 'Technical support roles across government departments. Requires specialized technical knowledge.',
    posts: 'Technical support, survey, data management',
    salary: '₦ 15,000 - 25,000',
    service_colors: ['#0891B2', '#7C3AED'],
  },
  {
    id: 5,
    slug: 'computer-operator',
    name: 'कम्प्युटर अपरेटर',
    en: 'Computer Operator',
    level: 'Technical',
    levelCode: 'technical',
    service: 'Office automation and typing test',
    papers: '2 Papers + Skill Test',
    vacancy: 'Limited openings',
    description: 'IT support and office automation. Includes practical typing and computer skills assessment.',
    posts: 'System management, data entry, IT support',
    salary: '₦ 14,000 - 20,000',
    service_colors: ['#0891B2', '#DC143C'],
  },
  {
    id: 6,
    slug: 'statistics-officer',
    name: 'तथ्याङ्क अधिकृत',
    en: 'Statistics Officer',
    level: 'Technical',
    levelCode: 'technical',
    service: 'Statistics and analytics',
    papers: '3 Papers',
    vacancy: 'Merit focused',
    description: 'Statistical analysis and data management. Requires strong mathematics and analytical skills.',
    posts: 'Data analysis, statistics, reporting',
    salary: '₦ 18,000 - 28,000',
    service_colors: ['#0891B2', '#10B981'],
  },
];

export const notes = [
  {
    id: 1,
    title: 'Nepal ko Samwidhan 2072 — Complete Notes',
    category: 'Constitution',
    color: '#10B981',
    exams: ['kharidar', 'nasu', 'sakha-adhikrit'],
    difficulty: 3,
    pages: 45,
    description: 'Full coverage of Nepal Constitution 2072 with all articles relevant to Loksewa exams.',
    file_url: null,
  },
  {
    id: 2,
    title: 'Shasan Pranali — Governance System Master Notes',
    category: 'Shasan Pranali',
    color: '#60A5FA',
    exams: ['nasu', 'sakha-adhikrit'],
    difficulty: 3,
    pages: 62,
    description: 'Federal structure, ministries, and administrative law complete guide.',
    file_url: null,
  },
  {
    id: 3,
    title: 'Samsamayik Bishaya 2082 — Current Affairs',
    category: 'Samsamayik',
    color: '#A78BFA',
    exams: ['nasu', 'sakha-adhikrit'],
    difficulty: 2,
    pages: 38,
    description: 'Updated current affairs for FY 2082 covering economy, environment, national events.',
    file_url: null,
  },
  {
    id: 4,
    title: 'General Knowledge — Nepal & World',
    category: 'GK',
    color: '#F59E0B',
    exams: ['kharidar', 'nasu', 'sakha-adhikrit'],
    difficulty: 1,
    pages: 80,
    description: 'Comprehensive GK: history, geography, science, and international affairs.',
    file_url: null,
  },
  {
    id: 5,
    title: 'Basic Mathematics & Aptitude',
    category: 'Aptitude',
    color: '#F87171',
    exams: ['kharidar', 'nasu'],
    difficulty: 2,
    pages: 55,
    description: 'Step-by-step math and aptitude with 200+ practice problems.',
    file_url: null,
  },
  {
    id: 6,
    title: 'Civil Service Act 2049 & Service Rules',
    category: 'Law & Acts',
    color: '#6EE7B7',
    exams: ['kharidar', 'nasu', 'sakha-adhikrit'],
    difficulty: 3,
    pages: 42,
    description: 'Complete guide to Civil Service Act, service rules, and administrative law.',
    file_url: null,
  },
  {
    id: 7,
    title: 'Office Management & Procedures',
    category: 'Office Mgmt',
    color: '#67E8F9',
    exams: ['kharidar', 'nasu'],
    difficulty: 1,
    pages: 30,
    description: 'File management, letter writing, record keeping, official communication.',
    file_url: null,
  },
  {
    id: 8,
    title: 'English Language — Grammar & Comprehension',
    category: 'English',
    color: '#60A5FA',
    exams: ['kharidar', 'nasu', 'sakha-abhikrit'],
    difficulty: 2,
    pages: 35,
    description: 'Grammar rules, vocabulary, and reading comprehension for all Loksewa levels.',
    file_url: null,
  },
];

export const serviceColors = {
  prasasan: '#1E40AF',
  pararastra: '#10B981',
  lekha: '#F59E0B',
  nyaya: '#7C3AED',
  sansad: '#DC143C',
  technical: '#0891B2',
};
